# Generated by Django 4.2.1 on 2023-06-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(db_column='id_comuna', primary_key=True, serialize=False)),
                ('name_comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(db_column='id_region', primary_key=True, serialize=False)),
                ('name_region', models.CharField(max_length=50)),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.CASCADE, to='Animalia.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnimalia',
            fields=[
                ('emailUsuario', models.EmailField(db_column='email_user', max_length=254, primary_key=True, serialize=False, unique=True)),
                ('nameUsuario', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
                ('region', models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='Animalia.region')),
            ],
        ),
    ]
