# Generated by Django 4.2.1 on 2023-06-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnimalia',
            fields=[
                ('emailUsuario', models.EmailField(db_column='email_user', max_length=254, primary_key=True, serialize=False, unique=True)),
                ('nameUsuario', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
        ),
    ]
