# Generated by Django 4.2.1 on 2023-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animalia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='id_comuna',
        ),
        migrations.AlterField(
            model_name='useranimalia',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
